-- Criação do banco de dados
CREATE DATABASE IF NOT EXISTS eletronicos_store;
USE eletronicos_store;

-- Criação da tabela de grupos de usuários
CREATE TABLE grupo_usuario (
    IDGRUPO INT PRIMARY KEY AUTO_INCREMENT,
    NOME ENUM('ADMINISTRADOR', 'ESTOQUISTA') NOT NULL
);

-- Criação da tabela de usuários
CREATE TABLE usuarios (
    IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CPF CHAR(14) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    STATUS TINYINT(1) DEFAULT 1,
    ID_GRUPO_USUARIO INT NOT NULL,
    FOREIGN KEY (ID_GRUPO_USUARIO) REFERENCES grupo_usuario(IDGRUPO)
);

-- Criação da tabela de produtos
CREATE TABLE produtos (
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    AVALIACAO DECIMAL(2,1) CHECK (AVALIACAO BETWEEN 1 AND 5),
    DESCRICAO TEXT,
    PRECO DECIMAL(10,2),
    QTD_ESTOQUE INT,
    STATUS TINYINT(1) DEFAULT 1
);

-- Criação da tabela de imagens dos produtos
CREATE TABLE imagem_produto (
    IDIMAGEM INT PRIMARY KEY AUTO_INCREMENT,
    CAMINHO VARCHAR(255) NOT NULL,
    PRINCIPAL BOOLEAN DEFAULT FALSE,
    ID_PRODUTO INT,
    FOREIGN KEY (ID_PRODUTO) REFERENCES produtos(IDPRODUTO)
);

CREATE TABLE clientes (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    SENHA VARCHAR(100) NOT NULL
);

CREATE TABLE enderecos_clientes (
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    CEP VARCHAR(255) NOT NULL,
    LOGRADOURO VARCHAR(255),
    COMPLEMENTO VARCHAR(255),
    UNIDADE VARCHAR(255),
    BAIRRO VARCHAR(255) NOT NULL,
    LOCALIDADE VARCHAR(255) NOT NULL,
    UF CHAR(2) NOT NULL,
    REGIAO VARCHAR(50),
    IBGE VARCHAR(100),
    GIA VARCHAR(100),
    DDD VARCHAR(10),
    SIAFI VARCHAR(10),
    TIPO_ENDERECO ENUM("F", "E") NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(IDCLIENTE)
);